#!/usr/local/bin/python3.0

import re
import os
import sys
import hashlib

import utility

if not os.path.exists("data/09"):
  os.makedirs("data/09")

readyfiles = {}
for path, dirs, files in os.walk("data/08"):
  readyfiles.update({file:os.path.join(path, file) for file in files})
print("Readyfiles isolated: %d" % len(readyfiles))

dumpfiles = {}
for path, dirs, files in os.walk("data/09"):
  dumpfiles.update({file:os.path.join(path, file) for file in files})
print("Dumpfiles isolated: %d" % len(dumpfiles))

touchfiles = sorted(set([tag for tag in readyfiles.keys()]) | set([tag for tag in dumpfiles.keys()]))

for tag in touchfiles:
  assert(tag in readyfiles)
  if not tag in dumpfiles:
    print("Dumping %s" % tag)
    
    ndat = utility.exe_bin("lua build_09_dump_core.lua %s" % readyfiles[tag])
    
    with open("data/09/%s" % (tag), "wb") as f:
      f.write(ndat)
