#!/usr/local/bin/python3.0

import re
import os
import sys

import utility
import S3

AWS_ACCESS_KEY_ID="1JC38J0QE1MGRE08TT82"
AWS_SECRET_ACCESS_KEY="+I7mvTFCcEpI1WZ14lDjVSaeog+BKBCVUudwIWKs"

BUCKET="questhelper_data"

conn = S3.AWSAuthConnection(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)
generator = S3.QueryStringAuthGenerator(AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY)

if not os.path.exists("data/01"):
  os.makedirs("data/01")

tregex = re.compile("rawdata_([0-9a-f]{32,32}).*\.bz2")
serverfiles = {tregex.match(x.key).group(1):x.key for x in utility.getAll(conn, BUCKET, "rawdata_00")}
print("Serverfiles isolated: %d" % len(serverfiles))

currentfiles = {}
for path, dirs, files in os.walk("data/01"):
  currentfiles.update({file:os.path.join(path, file) for file in files})
print("Currentfiles isolated: %d" % len(currentfiles))

touchfiles = sorted(set([tag for tag in currentfiles.keys()]) | set([tag for tag in serverfiles.keys()]))

for tag in touchfiles:
  assert(tag in serverfiles)
  if not tag in currentfiles:
    print("Downloading %s" % tag)
    dat = conn.get(BUCKET, serverfiles[tag]).object.data
    print("Downloaded, %d" % len(dat))
